/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf --transform 
Files: scene.gltf [27.49MB] > /Users/steve/Documents/Code/web/portfoliov2/public/models/golden-gate-bridge/scene-transformed.glb [4.45MB] (84%)
Author: damongraphics (https://sketchfab.com/damongraphics)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/golden-gate-bridge-3d-model-0f1bf2d780ad4cb6b4e0f4c650f6cdfc
Title: Golden Gate Bridge 3D Model
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Landscape_3_OctGlossy1_1_0.geometry} material={materials.OctGlossy1_1} position={[430.906, -27.759, -223.474]} scale={0.01} />
      <mesh geometry={nodes.Cube_2_1__0.geometry} material={materials.Cube_2_1__0} position={[462.745, 1.314, -108.854]} rotation={[Math.PI, 0.756, -Math.PI]} scale={0.003} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
